### ISSUE TITLE
can u help me set this up?

### ISSUE THREAD

**Issue by el211** [RedSmarty/ResourcePackConverter#1]
hey i am running geysermc on my server can u help me set this up ?
willing to pay ur feed

**Comment by el211** [comment]
like does that converts plugin ressources?

**Comment by BluMonkie** [comment]
This project is separate from GeyserMC, but it is used in my GeyserMC fork to support java resource packs. You should create an issue next time [here](https://github.com/RedSmarty/Geyser/issues) if you need help.
And to answer your question, yes it will automatically convert any resource pack placed in packs/java, or if you do not have a resource pack, you can fire up my fork of geyser and attempt to join the server which has custom resource packs. It will try to convert it automatically, and it should say **Changes should take effect next restart**. Just restart your geyser proxy and everything should work just fine. 
I am closing this issue, if you need any more help, feel free to open an issue on my fork repository, available on the link mentioned above.
Thanks.
